spring.application.name=e-commerce-lab
server.port = 9090

spring.datasource.url=jdbc:postgresql://localhost:5438/e-commerce
spring.datasource.username=e-commerce_user
spring.datasource.password=e-commerce_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false